name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.14.
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Export GOPATH.
        run: echo "::set-env name=GOPATH::$(go env GOPATH)"

      - name: Append GOPATH onto PATH.
        run: echo "::set-env name=PATH::$PATH:$GOPATH/bin"

      - name: Install golangci-lint.
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest

      - name: Start linter.
        run: golangci-lint -v run ./...

  test:
    steps:
      - name: Install Go 1.14.
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Start test.
        run: time go test -race -tags=integration ./...